# Generated by Django 4.2.7 on 2023-11-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endpoint",
            name="protocol",
        ),
        migrations.AddField(
            model_name="endpoint",
            name="protocols",
            field=models.ManyToManyField(
                related_name="endpoints", to="backend.protocol"
            ),
        ),
    ]
