# Generated by Django 4.2.7 on 2023-12-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endpoint",
            name="downstream_connections",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="upstream_connections",
        ),
        migrations.RemoveField(
            model_name="log",
            name="task",
        ),
        migrations.AddField(
            model_name="endpoint",
            name="connections",
            field=models.ManyToManyField(blank=True, null=True, to="backend.endpoint"),
        ),
    ]
