# Generated by Django 4.2.7 on 2023-12-30 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_remove_endpoint_downstream_connections_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="logs",
                to="backend.task",
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="definition_path",
            field=models.FileField(upload_to="files/agents"),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="files/files"),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="handler_path",
            field=models.FileField(upload_to="files/protocols"),
        ),
    ]
