# Generated by Django 4.2.7 on 2024-02-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "backend",
            "0003_log_task_alter_agent_definition_path_alter_file_file_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="definition_path",
            field=models.FileField(upload_to="agents"),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="files"),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="handler_path",
            field=models.FileField(upload_to="protocols"),
        ),
    ]
