# Generated by Django 4.2.7 on 2024-03-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "backend",
            "0003_log_task_alter_agent_definition_path_alter_file_file_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="definition_path",
        ),
        migrations.RemoveField(
            model_name="protocol",
            name="handler_path",
        ),
        migrations.AddField(
            model_name="agent",
            name="package_file",
            field=models.FileField(default="", upload_to="agents"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agent",
            name="package_path",
            field=models.FilePathField(
                allow_files=False,
                allow_folders=True,
                default="",
                path="packages/agents",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="protocol",
            name="package_file",
            field=models.FileField(default="", upload_to="protocols"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="protocol",
            name="package_path",
            field=models.FilePathField(
                allow_files=False,
                allow_folders=True,
                default="",
                path="packages/protocols",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="files"),
        ),
    ]
