# Generated by Django 4.2.7 on 2024-03-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_remove_agent_definition_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="version",
            field=models.CharField(
                default="0.0.1", help_text="The version for this agent.", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agent",
            name="name",
            field=models.CharField(
                help_text="Human-readable name for the agent.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="package_file",
            field=models.FileField(
                help_text="The original agent package file.", upload_to="agents"
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="package_path",
            field=models.FilePathField(
                allow_files=False,
                allow_folders=True,
                help_text="The directory in `packages/agents` where the agent's files have been unpackaged, with metadata generated.",
                path="packages/agents",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="package_file",
            field=models.FileField(
                help_text="The original protocol package file.", upload_to="protocols"
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="package_path",
            field=models.FilePathField(
                allow_files=False,
                allow_folders=True,
                help_text="The directory in `packages/protocols` where the protocol's files have been unpackaged, with metadata generated.",
                path="packages/protocols",
            ),
        ),
    ]
