# Generated by Django 4.2.7 on 2024-03-01 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_agent_version_alter_agent_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="agent",
            unique_together={("name", "version")},
        ),
    ]
