# Generated by Django 4.2.7 on 2024-03-07 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_remove_log_task_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endpoint",
            name="encryption_key",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="hmac_key",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="protocols",
        ),
        migrations.AddField(
            model_name="endpoint",
            name="payload_file",
            field=models.FileField(
                blank=True,
                help_text="The original payload bundle.",
                null=True,
                upload_to="payloads",
            ),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="address",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="endpoints",
                to="backend.agent",
            ),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="hostname",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
