# Generated by Django 4.2.7 on 2024-03-09 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_results", "0011_taskresult_periodic_task_name"),
        ("backend", "0008_remove_endpoint_encryption_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskresult",
            name="task",
        ),
        migrations.AlterField(
            model_name="credential",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credentials",
                to="django_celery_results.taskresult",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="files",
                to="django_celery_results.taskresult",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="logs",
                to="django_celery_results.taskresult",
            ),
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TaskResult",
        ),
    ]
