# Generated by Django 4.2.7 on 2024-03-14 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0009_remove_taskresult_task_alter_credential_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="protocol_state",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "message_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("timestamp", models.DateTimeField()),
                ("payload", models.JSONField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("CMD_RESPONSE", "command_response"),
                            ("CMD_REQUEST", "command_request"),
                            ("LOG_BUNDLE", "log_bundle"),
                            ("HEARTBEAT", "heartbeat"),
                        ],
                        max_length=50,
                    ),
                ),
                ("digest", models.BinaryField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="backend.endpoint",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
