# Generated by Django 4.2.7 on 2024-03-15 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0010_endpoint_protocol_state_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages_destinations",
                to="backend.endpoint",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages_sources",
                to="backend.endpoint",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
